# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and push to GHCR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    #- name: "Set up QEMU"
    #  uses: "docker/setup-qemu-action@v3"

    - name: "Set up Docker Buildx"
      uses: "docker/setup-buildx-action@v3"

    #- name: Build Docker image
    #  run: docker build -f ./GlosGuru/Dockerfile . -t ghcr.io/loxymartin/glosguru/glosguru:latest

    #- name: Log in to GitHub Packages
    #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    #- name: Tag Docker image
    #  run: docker tag myapp:latest ghcr.io/loxymartin/GlosGuru/glosguru:latest

    #- name: Push Docker image to GitHub Packages
    #  run: docker push ghcr.io/loxymartin/glosguru/glosguru:latest

    #- name: "Login to Docker Hub"
    #  uses: "docker/login-action@v3"
    #  with:
    #    username: "${{ secrets.DOCKERHUB_USERNAME }}"
    #    password: "${{ secrets.DOCKERHUB_TOKEN }}"
    - name: Log in to the ghcr
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set version variable
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: "Build and push image tags"
      uses: "docker/build-push-action@v6"
      with:
        file: "./GlosGuru.Web/Dockerfile"
        context: "."
        platforms: "linux/arm64"
        sbom: true
        push: true
        build-args: |
          VERSION=${{ env.VERSION }}
        tags: |
          "ghcr.io/loxymartin/glosguru/glosguru-web:latest"
          "ghcr.io/loxymartin/glosguru/glosguru-web:${{ env.VERSION }}"
